### ISSUE TITLE
KeyError: 'gitlab_plugin'

### ISSUE THREAD

**Issue by Lesego** [andreax79/airflow-gitlab-webhook#1]
Hi @andreax79 , 

Have you encountered any issues when installing using the gitlab plugin?

### **Reproduction Steps**
I am using airflow version 1.10.3. When installing the plugin using command "**pip install airflow-gitlab-webhook**", I run the into an error when it upgrade the airflow db "**airflow upgradedb**" or when I run the web server "**airflow webserver**". The main error seems to be: **KeyError: 'gitlab_plugin'**.

### **Full Error**
raceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/backports/configparser/__init__.py", line 1159, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'gitlab_plugin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 21, in <module>
    from airflow import configuration
  File "/usr/local/lib/python3.6/site-packages/airflow/__init__.py", line 91, in <module>
    operators._integrate_plugins()
  File "/usr/local/lib/python3.6/site-packages/airflow/operators/__init__.py", line 104, in _integrate_plugins
    from airflow.plugins_manager import operators_modules
  File "/usr/local/lib/python3.6/site-packages/airflow/plugins_manager.py", line 149, in <module>
    plugins
  File "/usr/local/lib/python3.6/site-packages/airflow/plugins_manager.py", line 89, in load_entrypoint_plugins
    plugin_obj = entry_point.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/airflow_gitlab_webhook/airflow_gitlab_webhook.py", line 53, in <module>
    plugin_config = get_plugin_config() # Plugin configuration
  File "/usr/local/lib/python3.6/site-packages/airflow_gitlab_webhook/airflow_gitlab_webhook.py", line 32, in get_plugin_config
    if not configuration.has_option(CONFIG_SECTION, 'REPOSITORY_URL' + suffix):
  File "/usr/local/lib/python3.6/site-packages/airflow/configuration.py", line 326, in has_option
    self.get(section, option, fallback=_UNSET)
  File "/usr/local/lib/python3.6/site-packages/airflow/configuration.py", line 283, in get
    self.airflow_defaults.get(section, key, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/backports/configparser/__init__.py", line 792, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.6/site-packages/backports/configparser/__init__.py", line 1162, in _unify_values
    raise NoSectionError(section)
backports.configparser.NoSectionError: No section: 'gitlab_plugin'

I have updated the config and it shows the section when I config looking at the config or the GUI:
[gitlab_plugin] 
repository_url = {{url}}
token = {{token}}
dag = tutorial

Im not sure if this plugin when installed will copy itself into the plugins folder set by the config. Currently it does not do so.

**Comment by joyenjoyer** [comment]
Hi @Lesego and @andreax79,

I can confirm that the same error pops up when you copy the plugin into the plugins folder manually. I tried it with Airflow 1.10.2 and 1.10.3 too.

**Comment by Lesego** [comment]
@crowgun 

Thank you for the update. I also tried copying the plugin into the folder with 1.10.3 and this didn't work as you mentioned above.

**Comment by joyenjoyer** [comment]
I am trying to write a plugin for Bitbucket and I found this repo so I was thinking this could be a solid base with a few changes. There might be something wrong about how Airflow loads those variables from the config file. I am looking into this so even if @andreax79 don't check this I might get back to you with something hopefully.

**Comment by andreax79** [comment]
Hi, I added a test virtualenv to the plugin in order to reproduce the problem. Airflow dependencies are realy broken :sob: (e.g. https://stackoverflow.com/questions/56933523/apache-airflow-airflow-initdb-throws-modulenotfounderror-no-module-named-wer )
- Airflow 1.10.4rc3 - no error
- Airflow 1.10.3 - No section: 'gitlab_plugin' exception - Something changed in some packages imported by Airflow since I developed the plugin

**Comment by andreax79** [comment]
Ok, fixed. Please try if it works for you.

**Comment by andreax79** [comment]
Fixed in version https://pypi.org/project/airflow-gitlab-webhook/1.0.1/
